#!/bin/bash

THEME_DIR="/usr/share/plymouth/themes/spinner"
BRANDING_DIR="/usr/share/equestria-os/branding"

# 1. Принудительно копируем водяной знак в тему spinner
if [ -d "$THEME_DIR" ]; then
    cp -f "$BRANDING_DIR/watermark.png" "$THEME_DIR/watermark.png"
fi

# 2. Переписываем глобальный конфиг Plymouth нашим эталоном
if [ -f "$BRANDING_DIR/plymouthd.conf" ]; then
    cp -f "$BRANDING_DIR/plymouthd.conf" /etc/plymouth/plymouthd.conf
fi

# 3. Принудительно выставляем тему spinner и запекаем её в initramfs ядер
plymouth-set-default-theme -R spinner
